### ISSUE TITLE
Restart always

### ISSUE THREAD

**Issue by xXjojaXx** [ORelio/Minecraft-Console-Client#1490]
Is there any possibility to make a script that detects when mcc isn't running, no matter if the server got shut down and now gets activated again or if a error occured that crashed the whole programm and restart it automatically, because we have to start our bot very regulary. Thanks ; )

**Comment by xXjojaXx** [comment]
And yes I know thats more an programming or linux question but google seems to hide this secret very deep, so I thought maybe you could help me

**Comment by ReinforceZwei** [comment]
You may write a script using other programming language such as Python or NodeJS to launch MCC and relaunch MCC if it crashes. Below is an untested Python code that would keep launching MCC in case MCC has stopped.
```python
import subprocess
while True:
    try:
        # replace .\\ with ./ if using Linux/MacOS
        subprocess.run(['.\\MinecraftClient.exe','BasicIO-NoColor'])
    except KeyboardInterrupt:
        exit()
```

Remember to set `exitonfailure=true` in your `MinecraftClient.ini` before using these kind of auto-restart script.

**Comment by ORelio** [comment]
I did something like this in the past on a Linux system:

**autorestart.sh**
```bash
#!/bin/bash
while true; do
    mono MinecraftClient.exe
    echo Restarting Minecraft Console Client...
    sleep 5
done
```

... which is very similar to what @ReinforceZwei did above, with `exitonfailure=true` in config. You can cancel the restart with Ctrl+C

**Comment by xXjojaXx** [comment]
Thank you for your answer. I will test it tomorrow

**Comment by SoundWreaking** [comment]
> 
> 
> You may write a script using other programming language such as Python or NodeJS to launch MCC and relaunch MCC if it crashes. Below is an untested Python code that would keep launching MCC in case MCC has stopped.
> 
> ```python
> import subprocess
> while True:
>     try:
>         # replace .\\ with ./ if using Linux/MacOS
>         subprocess.run(['.\\MinecraftClient.exe','BasicIO-NoColor'])
>     except KeyboardInterrupt: # allow Ctrl+C to exit
>         exit()
> ```
> 
> Remember to set `exitonfailure=true` in your `MinecraftClient.ini` before using these kind of auto-restart script.

How can I do this when I need to have two consle clients open?

**Comment by ReinforceZwei** [comment]
@SoundWreaking Start the above script twice.

**Comment by SoundWreaking** [comment]
> 
> 
> @SoundWreaking Start the above script twice.

Im too stupid :( Cant even get the script to run at all. Would you mind helping me, its probably something really easy but I cant figure it out. 

```
Traceback (most recent call last):
  File "c:\Users\Soundz\Desktop\CCAFK Handep\test.py", line 5, in <module>
    subprocess.run(['.\\MinecraftClient_2.exe','BasicIO-NoColor'])
  File "C:\Users\Soundz\AppData\Local\Programs\Python\Python39\lib\site-packages\run\__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
  File "C:\Users\Soundz\AppData\Local\Programs\Python\Python39\lib\site-packages\run\__init__.py", line 121, in create_process
    shlex.split(command),
  File "C:\Users\Soundz\AppData\Local\Programs\Python\Python39\lib\shlex.py", line 315, in split
    return list(lex)
  File "C:\Users\Soundz\AppData\Local\Programs\Python\Python39\lib\shlex.py", line 300, in __next__
    token = self.get_token()
  File "C:\Users\Soundz\AppData\Local\Programs\Python\Python39\lib\shlex.py", line 109, in get_token
    raw = self.read_token()
  File "C:\Users\Soundz\AppData\Local\Programs\Python\Python39\lib\shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'
```

**Comment by ReinforceZwei** [comment]
That's weird. The script works on my machine with Python 3.7.2. Please try again with the modified version below.
```py
import subprocess
while True:
    try:
        # replace .\\ with ./ if using Linux/MacOS
        subprocess.run('.\\MinecraftClient.exe BasicIO-NoColor')
    except KeyboardInterrupt: # allow Ctrl+C to exit
        exit()
```

**Comment by Soundz1337** [comment]
```
Traceback (most recent call last):
  File "c:\Users\Soundz\Desktop\CCAFK Handep\test.py", line 5, in <module>
    subprocess.run('.\\MinecraftClient_2.exe BasicIO-NoColor')
  File "C:\Users\Soundz\AppData\Local\Programs\Python\Python39\lib\site-packages\run\__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
  File "C:\Users\Soundz\AppData\Local\Programs\Python\Python39\lib\site-packages\run\__init__.py", line 120, in create_process
    return subprocess.Popen(
  File "C:\Users\Soundz\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Soundz\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

Still not working but Ill try to reinstall Python

**Comment by ReinforceZwei** [comment]
You have to put `MinecraftClient.exe` to the same folder of your script.

**Comment by Soundz1337** [comment]
> You have to put `MinecraftClient.exe` to the same folder of your script.

I do have it in the same folder. Just put the script into the Consoleclient Folder.

**Comment by xXjojaXx** [comment]
Did you copy the script from above. If yes type it by hand. May be an error because of an wrong byte error/space or new line etc.

**Comment by Soundz1337** [comment]
@xXjojaXx @ReinforceZwei 
![image](https://user-images.githubusercontent.com/43936650/111838474-aae06900-88f9-11eb-9815-221fbc6503e6.png)
![image](https://user-images.githubusercontent.com/43936650/111838528-bfbcfc80-88f9-11eb-9305-69861ffddec8.png)
![image](https://user-images.githubusercontent.com/43936650/111838562-cc415500-88f9-11eb-8dda-0e5509387d38.png)

Nope, still not working. I can launch it manually just fine but the code is just not working.

**Comment by ReinforceZwei** [comment]
@Soundz1337 You are not launching it at the right directory. You have to `cd` into your `MinecraftClient.exe` folder with powershell and run `py scriptname.py`

**Comment by Soundz1337** [comment]
> @Soundz1337 You are not launching it at the right directory. You have to `cd` into your `MinecraftClient.exe` folder with powershell and run `py scriptname.py`

Ohhhhhh I see, thanks a ton. Sorry for taking up your time with this little problem.
